[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_rust = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/atul/.config/solana/id.json"

[scripts]
test = "node tests/solana-rust.js"
