[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_rust = "yZnJDyXuzzVgmApz7aknGAhVFzPXrhNDwtodezFygJo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/atul/.config/solana/id.json"

[scripts]
test = "node tests/solana-rust.js"
